sudo: required

services:
  - docker

services:
  - docker

env:
  - TEST_SUITE=Unit
  - TEST_SUITE=Integration

script:
  - git checkout $TRAVIS_BRANCH
  - sh test-from-github-via-docker.sh $TEST_SUITE
